In [1]:
# 라이브러리 import
from keras.utils import np_utils
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense, Activation

import numpy as np

Using TensorFlow backend.
/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/dtypes.py:519: FutureWarn

## 1단계 데이터셋 생성하기

- 학습 시키려는 데이터를 로딩
- 학습 시키려는 데이터를 생성

여기서는 mnist 라는 유명한 손글씨 데이터를 가지고 오도록 함

In [2]:
# 데이터를 로딩
(x_train, y_train) , (x_test, y_test) = mnist.load_data()

np.set_printoptions(linewidth=np.inf)# 한줄 출력을 위한 것

# 그중에 첫번째 데이터가 무엇인가를 확인
print("트레이닝 데이터셋 인풋 : ")
print(x_train[0])
print("트레이닝 데이터셋 정답 : "+ str(y_train[0]))

트레이닝 데이터셋 인풋 : 
[[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   3  18  18  18 126 136 175  26 166 255 247 127   0   0   0   0]
 [  0   0   0   0   0   0   0   0  30  36  94 154 170 253 253 253 253 253 225 172 253 242 195  64   0   0   0   0]
 [  0   0   0   0   0   0   0  49 238 253 253 253 253 253 253 253 253 251  93  82  82  56  39   0   0   0   0   0]
 [  0   0   0   0   0   0   0  18 219 253 253 253 253 253 198 18

mnist 는 6만개의 학습셋과 1만개의 테스트 셋으로 구성 되어있습니다.

In [3]:
print(x_train.shape)
print(y_train.shape)

(60000, 28, 28)
(60000,)


In [4]:
# 한줄로 쭉 펴준다

x_train = x_train.reshape(60000,784).astype('float32') / 255.0
x_test = x_test.reshape(10000,784).astype('float32') / 255.0

# x_train = x_train.reshape(-1,784).astype('float32')
# x_test = x_test.reshape(-1,784).astype('float32')

print(x_train[0])
print(y_train[0])

[0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.         0.       

원 핫 인코딩으로 변경

In [5]:
y_train = np_utils.to_categorical(y_train)
y_test = np_utils.to_categorical(y_test)

print(y_train.shape)
print(y_train[0])

(60000, 10)
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


# 2 단계 모델 구성하기

입력층과 출력층이 있는 간단한 모델을 구성해봅니다.

In [6]:
model = Sequential()
model.add(Dense(units=64,input_dim=28*28, activation='relu'))
model.add(Dense(10,activation='softmax'))

# 3단계 모델 학습과정 설정하기

In [7]:
model.compile(loss='categorical_crossentropy',optimizer='sgd',metrics=['accuracy'])

# 4단계 모델 학습 시키기

In [8]:
hist = model.fit(x_train,y_train,epochs=100,batch_size=32)

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where

Epoch 1/100
60000/60000 [==============================] - 1s 24us/step - loss: 0.6804 - acc: 0.8284
Epoch 2/100
60000/60000 [==============================] - 1s 22us/step - loss: 0.3407 - acc: 0.9041
Epoch 3/100
60000/60000 [==============================] - 1s 21us/step - loss: 0.2939 - acc: 0.9160
Epoch 4/100
60000/60000 [==============================] - 1s 21us/step - loss: 0.2655 - acc: 0.9243
Epoch 5/100
60000/60000 [==============================] - 1s 20us/step - loss: 0.2438 - acc: 0.9306
Epoch 6/100
60000/60000 [==============================] - 1s 20us/step - loss: 0.2259 - acc: 0.9357
Epoch 7/100
60000/60000 [==============================] - 1s 20us/step - loss: 0.2105 - acc: 0.9407
Epoch 8/100
60000/60000 [==============================] - 1s 20us/step - loss: 0.1972 - acc: 0.9448
Epoch 9/100
60000/60000 [==============================] - 1s 20us/step - loss: 0.1860 - acc: 0.9

60000/60000 [==============================] - 1s 20us/step - loss: 0.0417 - acc: 0.9892
Epoch 76/100
60000/60000 [==============================] - 1s 20us/step - loss: 0.0410 - acc: 0.9898
Epoch 77/100
60000/60000 [==============================] - 1s 20us/step - loss: 0.0406 - acc: 0.9901: 0s - loss: 0.0397 - acc:
Epoch 78/100
60000/60000 [==============================] - 1s 20us/step - loss: 0.0401 - acc: 0.9899
Epoch 79/100
60000/60000 [==============================] - 1s 20us/step - loss: 0.0396 - acc: 0.9902
Epoch 80/100
60000/60000 [==============================] - 1s 20us/step - loss: 0.0390 - acc: 0.9905
Epoch 81/100
60000/60000 [==============================] - 1s 20us/step - loss: 0.0386 - acc: 0.9907
Epoch 82/100
60000/60000 [==============================] - 1s 20us/step - loss: 0.0380 - acc: 0.9905
Epoch 83/100
60000/60000 [==============================] - 1s 20us/step - loss: 0.0377 - acc: 0.9908
Epoch 84/100
60000/60000 [==============================] - 1s 20us/s

# 5  단계 학습과정 

In [10]:
print(hist.history['loss'])
print(hist.history['acc'])

[0.6804139303485552, 0.3407434992512067, 0.293933588685592, 0.26553983776172, 0.24378695451418558, 0.2259015962064266, 0.2104771410961946, 0.19722544400791328, 0.1859502805372079, 0.17568728145261606, 0.16652095077633858, 0.15864784305294355, 0.15167587526887655, 0.14500639741569757, 0.13922734645505747, 0.1337443397089839, 0.12860041798204183, 0.12403766309171915, 0.11986998798499504, 0.1157762305577596, 0.11218396802395582, 0.1087376074001193, 0.10543086368938287, 0.10242060128897429, 0.09973583492860198, 0.0969138585664332, 0.09462280704999963, 0.09210547064393759, 0.08971821000600855, 0.08764100398967664, 0.08555198883687457, 0.08357964648505052, 0.081822563012441, 0.08007577159230908, 0.07839560136223833, 0.0767732985506455, 0.0753233414883415, 0.07371758064205448, 0.07226801368867358, 0.07091684971352419, 0.06959002556068201, 0.06838236949245136, 0.06719933866535624, 0.06591973305580516, 0.06467352732457221, 0.06373101586264869, 0.06260208520392577, 0.06163482335228473, 0.0607430

# 6단계 모델 평가하기

In [11]:
loss_and_metrics = model.evaluate(x_test,y_test,batch_size=32)
print(loss_and_metrics)

10000/10000 [==============================] - 0s 11us/step
[0.08191094595703761, 0.9749]


# 7단계 모델 사용하기

In [19]:
xhat = x_test[0:1]
y = y_test[0:1]

yhat = model.predict(xhat)

print((yhat*10/9).astype('int'))
print(y.astype('int'))

[[0 0 0 0 0 0 0 1 0 0]]
[[0 0 0 0 0 0 0 1 0 0]]
